spring:
    datasource:
        initialization-mode: always
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/aesonline?serverTimezone=Europe/Madrid
        username: api
        password: n_nslp0nssAA22q3aq1!
    jpa:
        hibernate:
            ddl-auto: update
    resources:
        static-locations: classpath:/static/

wca:
    callbackUrlLogin: https://aesonline.speedcubingspain.org/loginInicio
    callbackUrlSoloValidar: https://aesonline.speedcubingspain.org/validar
    clientId: _Syvq_7EhXMViil3G0nygoCBTZzpeGL95uJXkpwJgCQ
    clientSecret: JaDvrqQEUyIYShejo2ZLxqhpIqizmNowvwNb7iaHMQE

logging:
    file:
        path: /root/log
    level:
        org.hibernate.SQL: error






