spring:
  datasource:
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aesonline?serverTimezone=Europe/Madrid
    username: root
    password: karateka123
  jpa:
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: detect

wca:
  callbackUrlLogin: http://localhost:8080/loginInicio
  callbackUrlSoloValidar: http://localhost:8080/validar
  clientId: 0YekXxbT20En0V96-cr-bmmTk9pGam2K9HvIA0fTPP0
  clientSecret: cm_cAljWpZTzAplkoDt3xG4KDWxjhGNICxzAwNKqFMg


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO

server:
  error:
    whitelabel:
      enabled: false

aesonline:
  enableEnvioTiempos: true


