spring:
  datasource:
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aesparticipantes?serverTimezone=Europe/Madrid
    username: root
    password: karateka123
#    data: classpath:sql/aesparticipantes_participantes.sql
  jpa:
    hibernate:
      ddl-auto: create
