spring:
  datasource:
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aesparticipantes?serverTimezone=Europe/Madrid
    username: root
    password: karateka123
  #    data: classpath:sql/aesparticipantes_participantes.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
#  security:
#    oauth2:
#      client:
#        registration:
#          wca:
#            client-id: 0YekXxbT20En0V96-cr-bmmTk9pGam2K9HvIA0fTPP0
#            client-secret: cm_cAljWpZTzAplkoDt3xG4KDWxjhGNICxzAwNKqFMg
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/loginWCA'
#        provider:
#           wca:
#             authorization-uri: https://www.worldcubeassociation.org/oauth/authorize
#             token-uri: https://www.worldcubeassociation.org/api/v0/me


wca:
  callbackUrl: http://localhost:8080/loginWCA
  callbackUrlSoloValidar: http://localhost:8080/validar
  clientId: 0YekXxbT20En0V96-cr-bmmTk9pGam2K9HvIA0fTPP0
  clientSecret: cm_cAljWpZTzAplkoDt3xG4KDWxjhGNICxzAwNKqFMg


#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQLDialect


server: #TODO error/404, los 500 distintos etc
  error:
    whitelabel:
      enabled: false


